### ISSUE TITLE
Tiene sentido que los sectoresPublico y privado sen Float?

### ISSUE THREAD

**Issue by natoszme** [nahuelDolian/FMI#1]
https://github.com/nahuelDolian/FMI/blob/cd4a28b04b55bdc5d89223e8063c7f456db72017/FMI.hs#L1

**Comment by nahuelDolian** [comment]
pasa que en algun momento los hacia multiplicar por una fraccion, y me decía que lo corrija

**Comment by natoszme** [comment]
Ah oka en el parcial si vas a hacer algo así aclaralo!
