### ISSUE TITLE
Por lo que entiendo del enunciado, recortarSectorPublico debería hacerse después de dar el préstamo

### ISSUE THREAD

**Issue by natoszme** [nahuelDolian/FMI#8]
https://github.com/nahuelDolian/FMI/blob/cd4a28b04b55bdc5d89223e8063c7f456db72017/FMI.hs#L34

**Comment by nahuelDolian** [comment]
creo que no, porque:
establecer un “blindaje”, lo que provoca prestarle a dicho país la mitad de su Producto Bruto Interno (que se calcula como el ingreso per cápita multiplicado por su población activa, sumando puestos públicos y privados de trabajo) y reducir 500 puestos de trabajo del sector público. Evitar la repetición de código. 
cuando se restan puesto de trabajo, se modifica automaticamente el PBI, yo creo que primero primero se recortan los puestos, despues se calcula el PBI, despues se da el prestamo respectivo..
quiza me equivoque! yo lo entendi asi

**Comment by natoszme** [comment]
Yo lo decía porque dice "...prestarle al país... y reducir 500 puestos de trabajo...". Sólo porque el "y" está después de la parte que habla de prestar. Pero es menor. Por las dudas, en el parcial pregunta esto ante la duda!
